### ISSUE TITLE
Avoid global state

### ISSUE THREAD

**Issue by ghost** [MityaSaray/clojure-tdlib-json#4]
Now the lib store client and message queue in global bindings. I think will be better use different clients for this.
E.g.
``` clojure
(defn create-client [path-to-lib timeout buffer-size]
  {:client (TgClient. path-to-lib timeout)
    :message-queue (async/chan (async/buffer buffer-size))})

(defn client-send [client messageMap]
  (. (:client client) send (jsonify messageMap)))

(defn init-reader-loop [client]
  (async/go-loop [c client]
    (let [message (client-receive c)]
      (when-not (nil? message)
        (async/>! (:message-queue c) message))
      (recur c))))
```

**Comment by MityaSaray** [comment]
I am not sure and i dont remember if it is possible to have multiple clients with current native process implementation.
I will take a look soonish

**Comment by ghost** [comment]
I was try to do this:
https://github.com/Lamppilutti/clojure-tdlib-json/blob/multiple-clients/src/clojure/tdlib_json/core.clj
Looks like it works.

**Comment by ghost** [comment]
Ok, there realy are problems with the log file, when multiple clients are used. But I still think that avoiding global state is better and add note to `create-client` docstring is enough for the wrapper.

**Comment by ghost** [comment]
Also, maybe better use new tdlib json interface (or use both) and remove the async loop? Users will have all state controll and the lib will just thin wrapper for easy acces to the tdlib json.

**Comment by MityaSaray** [comment]
Yes, it would be nice to provide ability to select your own transport. With default as now and optional provision of your own reader loop implementation

**Comment by ghost** [comment]
So, what about stop store state?

**Comment by MityaSaray** [comment]
I think i am going to make a description for create-client function and provide overload for all send/execute/recieve/destroy functions that will accept client as an argument

**Comment by MityaSaray** [comment]
@Lamppilutti https://github.com/MityaSaray/clojure-tdlib-json/pull/7 does this close this issue?

**Comment by ghost** [comment]
Yes, thank you.
